{{- if and .Values.c2c.enabled .Values.c2c.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c2c
  annotations:
{{- toYaml .Values.c2c.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.c2c.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c2c
                port:
                  number: 80
  tls:
{{- toYaml .Values.c2c.ingress.tls | nindent 4 }}
{{ end -}}