{{- if .Values.bro.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bro
  annotations:
{{ .Values.bro.annotations | toYaml | indent 4 }}
spec:
  selector:
    matchLabels:
      app: bro
  replicas: 1
  revisionHistoryLimit: {{ .Values.common.revisionHistoryLimit }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bro
    spec:
      containers:
      - name: mirotalk
        image: "{{ .Values.bro.image.name }}:{{ .Values.bro.image.tag }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common
        - secretRef:
            name: {{ .Values.common.existingSecret | default "common" }}
{{ end -}}