{{- if and .Values.sfu.enabled }}
{{- if not .Values.sfu.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sfu
type: Opaque
stringData:
  RTMP_STREAM_KEY: ''                             # RTMP stream key (optional)
  RTMP_SECRET: 'mirotalkRtmpSecret'               # RTMP API secret (Must match node-media-server config.js)
  RTMP_API_SECRET: 'mirotalkRtmpApiSecret'        # RTMP internal secret
  USERS_API_SECRET: 'mirotalkweb_default_secret'  # Users API secret key
  DEFAULT_USERNAME: 'admin'                       # Default admin username
  DEFAULT_PASSWORD: 'niomda'                      # Default admin password
  DEFAULT_DISPLAY_NAME: 'Administrators'          # Default display name
  DEFAULT_ALLOWED_ROOMS: '*'                      # Default allowed rooms all or room1,room2... (comma-separated)
{{ end -}}
{{ end -}}