{{- if .Values.p2p.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p
  annotations:
{{ .Values.p2p.annotations | toYaml | indent 4 }}
spec:
  selector:
    matchLabels:
      app: p2p
  replicas: 1
  revisionHistoryLimit: {{ .Values.common.revisionHistoryLimit }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2p
    spec:
      containers:
      - name: mirotalk
        image: "{{ .Values.p2p.image.name }}:{{ .Values.p2p.image.tag }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common
        - secretRef:
            name: {{ .Values.common.existingSecret | default "common" }}
{{ end -}}