{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
{{- toYaml .Values.web.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
  tls:
{{- toYaml .Values.web.ingress.tls | nindent 4 }}
{{ end -}}