{{- if and .Values.web.enabled }}
{{- if not .Values.web.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web
type: Opaque
stringData:
  # WEB only
  # MongoDB
  MONGO_USERNAME: blabla
  MONGO_PASSWORD: asdfghwrtes
  MONGO_URL: mongodb://blabla:asdfghwrtes@mongodb:27017
{{ end -}}
{{ end -}}