{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: web
{{ end -}}
{{- if .Values.mongodb.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
{{ end -}}